services:
  _defaults:
    autowire: true
    autoconfigure: true

  Danilovl\OpenTelemetryBundle\:
    resource: '../../*'
    exclude:
      - '../../DependencyInjection'
      - '../../Instrumentation/**/Metrics'
      - '../../Instrumentation/**/LongRunningCommand'
      - '../../Instrumentation/Interfaces'
      - '../../Instrumentation/Redis'
      - '../../Instrumentation/Symfony/HttpClient'
      - '../../Instrumentation/Symfony/Messenger'
      - '../../Instrumentation/Symfony/Mailer'
      - '../../Instrumentation/Symfony/Twig'
      - '../../Instrumentation/Symfony/Console'
      - '../../Instrumentation/Symfony/Traceable'
      - '../../Instrumentation/Symfony/HttpKernel'
      - '../../Instrumentation/Symfony/Cache'
      - '../../Instrumentation/Symfony/EventDispatcher'
      - '../../Instrumentation/Async'
      - '../../Instrumentation/Doctrine'
      - '../../Model'
      - '../../OpenTelemetry/Attribute'
      - '../../OpenTelemetry/Helper'
      - '../../OpenTelemetry/Interfaces'
      - '../../OpenTelemetry/Service/MetricsRecorder.php'
